### ISSUE TITLE
feat: interpolate values from environment

### ISSUE THREAD

**Issue by rgelinas-polygon** [0xPolygon/panoptichain#9]
Being able to pull config values from the environment would make it easier to obscure "secret" values (private RPC URls, private keys, etc.) in production environments. For example:

```yaml
providers:
  rpc:
    - name: "Test Network"
       url: "$PRIVATE_RPC_URL" # could be another construct, this mimics shell env var interpolation
       label: "dummy-rpc"
```
This would allow operators to inject RPC URLs with private API keys and other secret values without codifying them in the config.
